config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}
  resources :users, only: [:index, :edit, :update, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")

  get "/home", to: "web#index"
  get "/dashboard", to: "web#dashboard"

  resources :units do
    member do
      get "sectors"
      get "visits", to: "units#visits"
    end
  end
  resources :sectors do
    member do
      get "users"
    end
  end
  resources :visitors do
    collection do
      post :verify_by_cpf
    end
  end
  resources :visits

  root "web#index"
end

app/models/visit.rb
class Visit < ApplicationRecord
  validates :visitor_id, presence: true
  validates :unit_id, presence: true
  validates :sector_id, presence: true
  validates :user_id, presence: false
  validates :date_time, presence: true
  validates :status, presence: true

  validate :date_time_is_not_in_the_past

  enum :status, {pending: 0, completed: 1, absent: 2}

  belongs_to :visitor
  belongs_to :unit
  belongs_to :sector
  belongs_to :user, optional: true

  def date_time_is_not_in_the_past
    if date_time.present? && date_time < Time.current
      errors.add(:date_time, "the visit cannot be on a past date")
    end
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_visit, only: [:show]

  def index
  end

  def show
  end

  def new
    @visit = Visit.new
  end

  def edit
  end

  def update
    if @visit.update(visit_params)
      flash[:notice] = "Visit updated successfully"
      redirect_to visit_path
    else
      flash[:alert] = @visit.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @visit.destroy
    flash[:notice] = "Visitor destroyed successfully"
    redirect_to visits_path
  end

  def create
    @visit = Visit.new(visit_params)
    if @visit.save
      flash[:notice] = "Visit created successfully"
      redirect_to visits_path
    else
      flash[:alert] = @visit.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  private

  def visit_params
    params.expect(visit: [:visitor_id, :unit_id, :sector_id, :user_id, :date_time, :status])
  end

  def set_visit
    @visit = Visit.find(params[:id])
  end
end

app/helpers/visit_helper.rb
module VisitHelper
end

app/views/visits/_form.html.erb
<%= form_with model: @visit, class: "bg-gray-700 p-6 rounded-lg shadow-md" do |visit| %>
    
    <div class="mb-4">
        <%= visit.label :visitor_id, "Visitor", class: "block text-white text-lg font-medium mb-2"%>
        <%= visit.collection_select :visitor_id, Visitor.all, :id, :name, { prompt: "Select the visitor" }, class: "w-full p-2 rounded-lg bg-gray-800 text-white border border-gray-600 focus:ring-2 focus:ring-blue-500 focus:outline-none"%>
    </div>

    <div class="mb-4">
    <%= visit.label :unit_id, "Unit", class: "block text-white text-lg font-medium mb-2" %>
    <% if current_user.admin? %>
        <%= visit.collection_select :unit_id, Unit.all, :id, :name, { prompt: "Select the unit" }, id: "unit_select", class: "w-full p-2 rounded-lg bg-gray-800 text-white border border-gray-600 focus:ring-2 focus:ring-blue-500 focus:outline-none" %>
    <% else %>
        <%= visit.collection_select :unit_id, Unit.where(id: current_user.unit_id), :id, :name, { prompt: "Select the unit" }, id: "unit_select", class: "w-full p-2 rounded-lg bg-gray-800 text-white border border-gray-600 focus:ring-2 focus:ring-blue-500 focus:outline-none" %>
    <% end %>
    </div>

    <div class="mb-4">
        <%= visit.label :sector_id, "Sector", class: "block text-white text-lg font-medium mb-2"%>
        <%= visit.collection_select :sector_id, [], :id, :name, { prompt: "Select the sector" }, id: "sector_select", class: "w-full p-2 rounded-lg bg-gray-800 text-white border border-gray-600 focus:ring-2 focus:ring-blue-500 focus:outline-none"%>
    </div>

    <div class="mb-4">
        <%= visit.label :user_id, "Functionario", class: "block text-white text-lg font-medium mb-2"%>
        <%= visit.collection_select :user_id, [], :id, :name, { prompt: "Select the functionario" }, id: "user_select", class: "w-full p-2 rounded-lg bg-gray-800 text-white border border-gray-600 focus:ring-2 focus:ring-blue-500 focus:outline-none"%>
    </div>

    <div class="mb-4">
        <%= visit.label :status, "Status", class: "block text-white text-lg font-medium mb-2"%>
        <%= visit.select :status, Visit.statuses.keys.map { |s| [s.humanize, s] }, { prompt: "Select the status" }, class: "w-full p-2 rounded-lg bg-gray-800 text-white border border-gray-600 focus:ring-2 focus:ring-blue-500 focus:outline-none"%>
    </div>

    <div class="mb-4">
        <%= visit.label :date_time, "Date e Time", class: "block text-white text-lg fontSelect-medium mb-2"%>
        <%= visit.datetime_field :date_time, class: "w-full p-2 rounded-lg bg-gray-800 text-white border border-gray-600 focus:ring-2 focus:ring-blue-500 focus:outline-none" %>
    </div>

    <div>
        <%= visit.submit "Save", class: "w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-lg transition"%>
    </div>
<% end %>

<script>
    document.addEventListener('turbo:load', function() {
    const unitSelect = document.getElementById('unit_select');
    const sectorSelect = document.getElementById('sector_select');
    const userSelect = document.getElementById('user_select');

    if (unitSelect) {
        unitSelect.addEventListener('change', function() {
            const unitId = this.value;
            fetch(`/units/${unitId}/sectors`)
                .then(response => response.json())
                .then(data => {
                    sectorSelect.innerHTML = '<option value="">Select the sector</option>';
                    data.forEach(sector => {
                        const option = document.createElement('option');
                        option.value = sector.id;
                        option.text = sector.name;
                        sectorSelect.appendChild(option);
                    });
                });
        });
    }

    if (sectorSelect) {
        sectorSelect.addEventListener('change', function() {
            const sectorId = this.value;
            fetch(`/sectors/${sectorId}/users`)
                .then(response => response.json())
                .then(data => {
                    userSelect.innerHTML = '<option value="">Select the functionario</option>';
                    data.forEach(user => {
                        const option = document.createElement('option');
                        option.value = user.id;
                        option.text = user.name;
                        userSelect.appendChild(option);
                    });
                });
        });
    }
});
</script>

app/views/visits/edit.html.erb
<div class="max-w-3xl mx-auto bg-gray-800 text-white p-6 rounded-lg shadow-lg mt-6">
    <h1 class="text-3xl font-bold mb-6">Edit Visit</h1>

    <div class="mb-6">
        <%= render "form", visit: @visit%>
    </div>

    <div class="mb-4">
        <%= link_to "Cancel", visit_path, class: "bg-gray-600 hover:bg-gray-700 px-4 py-2 rounded-lg transition"%>
    </div>

</div>

app/views/visits/index.html.erb
<div class="max-w-4xl mx-auto bg-gray-800 text-white p-6 rounded-lg shadow-lg mt-6">
  <h1 class="text 3xl font-bold mb-6">Visits</h1>

  <div class="space-y-4"id="visits">
    <% @visits.pending.each do |visit|%>
      <div class="bg-gray-700 p-4 rounded-lg hover:bg-gray-600 transition">
        <%= link_to "#{visit.visitor.name} - #{visit.date_time.strftime('%d/%m/%Y %H:%M')}", visit, class: "text-lg font-medium text-blue-400 hover:underline" %>
      </div>
    <%end%>
  </div>

  <% if can? :create, Visit %>
    <div class="mt-6">
      <%= link_to 'New Visit', new_visit_path, class: "bg-green-600 hover:bg-green-700 px-4 py-2 rounded-lg transition" %>
    </div>
  <% end %>
</div>

app/views/visits/new.html.erb
<div class="max-w-3xl mx-auto bg-gray-800 text-white p-6 rounded-lg shadow-lg mt-6">
    <h1 class="text-3xl font-bold mb-6">Create new Visitor</h1>

    <div class="mb-6">
        <%= render "form", visit: @visit%>
    </div>

    <div class="mb-4">
        <%= link_to "Cancel", visits_path, class: "bg-gray-600 hover:bg-gray-700 px-4 py-2 rounded-lg transition"%>
    </div>

</div>

app/views/visits/show.html.erb
<div class="max-w-2xl mx-auto bg-gray-800 text-white p-6 shadow-md rounded-lg mt-6">
    <h1 class="text-2xl font-bold mb-4">Visit data</h1>
    <p class="text-lg text-gray-300 mb-2">Visitor name: <%= link_to @visit.visitor.name, visitor_path(@visit.visitor.id), class: "hover:underline text-blue-400"%></p>
    <p class="text-lg text-gray-300 mb-2">Unit: <%= link_to @visit.unit.name, unit_path(@visit.unit.id), class: "hover:underline text-blue-400"%></p>
    <p class="text-lg text-gray-300 mb-2">Sector: <%= link_to @visit.sector.name, sector_path(@visit.sector.id), class: "hover:underline text-blue-400"%></p>
    <p class="text-lg text-gray-300 mb-2">Employee: <%= @visit.user&.name || "Not specified" %></p>
    <p class="text-lg text-gray-300 mb-2">Visit Date: <%= @visit.date_time%></p>
    <p class="text-lg text-gray-300 mb-2">Status: <%= @visit.status%></p>

    <div class="flex space-x-4">
        <%= link_to 'Back', visits_path, class: "bg-gray-600 hover:bg-gray-700 px-4 py-2 rounded-lg transition" %>

        <% if can? :update, Visit %>
            <%= link_to "Edit vist", edit_visit_path, class: "bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg transition"%>
        <% end %>
        <% if can? :destroy, Visit %>
            <%= button_to "Delete", @visit, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "bg-red-600 hover:bg-red-700 px-4 py-2 rounded-lg transition" %>
        <% end %>
    </div>

</div>