config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}
  resources :users, only: [:index, :edit, :update, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")

  get "/home", to: "web#index"
  get "/dashboard", to: "web#dashboard"

  resources :units do
    member do
      get "sectors"
      get "visits", to: "units#visits"
    end
  end
  resources :sectors do
    member do
      get "users"
    end
  end
  resources :visitors do
    collection do
      post :verify_by_cpf
    end
  end
  resources :visits

  root "web#index"
end

app/models/unit.rb
class Unit < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  has_many :sectors
  has_many :visits
  has_many :users
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_unit, only: [:edit, :update, :show, :destroy]

  def index
    @units = Unit.all
  end

  def show
  end

  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new(unit_params)
    if @unit.save
      flash[:notice] = "Unit created successfully"
      redirect_to units_path
    else
      flash[:alert] = @unit.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @unit.update(unit_params)
      flash[:notice] = "Sector updated successfully"
      redirect_to units_path
    else
      flash[:alert] = @unit.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @unit.destroy
    flash[:notice] = "Unit deleted successfully"
    redirect_to units_path
  end

  def sectors
    unit = Unit.find(params[:id])
    sectors = unit.sectors
    render json: sectors
  end

  def visits
    @unit = Unit.find(params[:id])
    @visits = @unit.visits
  end

  private

  def unit_params
    params.expect(unit: [:name, :email])
  end

  def set_unit
    @unit = Unit.find(params[:id])
  end
end

app/helpers/unit_helper.rb
module UnitHelper
end

app/views/units/_form.html.erb
<%= form_with model: @unit, class: "bg-gray-700 p-6 rounded-lg shadow-md" do |unit| %>
    <div class="mb-4">
        <%= unit.label :name, class: "block text-white text-lg font-medium mb-2" %>
        <%= unit.text_field :name, class: "w-full p-2 rounded-lg bg-gray-800 text-white border border-gray-600 focus:ring-2 focus:ring-blue-500 focus:outline-none " %><br>
    </div>

    <div class="mb-4">
        <%= unit.label :email, class: "block text-white text-lg font-medium mb-2" %>
        <%= unit.email_field :email, class: "w-full p-2 rounded-lg bg-gray-800 text-white border border-gray-600 focus:ring-2 focus:ring-blue-500 focus:outline-none " %>
    </div>

    <div class="mb-6">
        <%= unit.submit "Save", class: "w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-lg transition" %>
    </div>
<% end %>

app/views/units/edit.html.erb
<div class="max-w-3xl mx-auto bg-gray-800 text-white p-6 rounded-lg shadow-lg mt-6">
    <h1 class="text-3xl font-bold mb-6">Edit Unit</h1>

    <div class="mb-6">
        <%= render "form", unit: @unit %>
    </div>

    <div class="mb-4">
        <%= link_to 'Cancel', unit_path, class: "bg-gray-600 hover:bg-gray-700 px-4 py-2 rounded-lg transition" %>
    </div>

</div>

app/views/units/index.html.erb
<div class="max-w-4xl mx-auto bg-gray-800 text-white p-6 rounded-lg shadow-lg mt-6">
  <h1 class="text 3xl font-bold mb-6">Units</h1>

  <div class="space-y-4" id="units">
    <% @units.each do |unit| %>
      <div class="bg-gray-700 p-4 rounded-lg hover:bg-gray-600 transition flex justify-between items-center">
        <%= link_to unit.name, unit, class: "text-lg font-medium text-blue-400 hover:underline" %>  
        <h2 class="text-lg font-medium text-blue-400 hover:underline"><%= link_to "Visits", visits_unit_path(unit) %></h2>
      </div>
    <% end %>
  </div>

  <% if can? :create, Unit %>
    <div class="mt-6">
    <%= link_to 'New Unit', new_unit_path, class: "bg-green-600 hover:bg-green-700 px-4 py-2 rounded-lg transition" %>
    </div>
  <% end %>
</div>

app/views/units/new.html.erb
<div class="max-w-3xl mx-auto bg-gray-800 text-white p-6 rounded-lg shadow-lg mt-6">
    <h1 class="text-3xl font-bold mb-6">Create new Unit</h1>

    <div class="mb-6">
        <%= render "form", unit: @unit %>
    </div>

    <div class="mb-4">
        <%= link_to 'Cancel', units_path, class: "bg-gray-600 hover:bg-gray-700 px-4 py-2 rounded-lg transition" %>
    </div>
</div>

app/views/units/show.html.erb
<div class="max-w-2xl mx-auto bg-gray-800 text-white p-6 shadow-md rounded-lg mt-6">
    <h1 class="text-2xl font-bold mb-4">Unit data</h1>
    <p class="text-lg text-gray-300 mb-2">Name: <%= @unit.name %></p>
    <p class="text-lg text-gray-300 mb-2">Email: <%= @unit.email %></p>

    <div class="flex space-x-4">
        <%= link_to 'Back', units_path, class: "bg-gray-600 hover:bg-gray-700 px-4 py-2 rounded-lg transition" %>
        <% if can? :manage, Unit %>
            <%= link_to 'Edit unit', edit_unit_path(@unit), class: "bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg transition"%>
            <%= button_to "Delete", @unit, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "bg-red-600 hover:bg-red-700 px-4 py-2 rounded-lg transition" %>
        <% end %>
    </div>
</div>

app/views/units/visits.html.erb
<div class="max-w-4xl mx-auto bg-gray-800 text-white p-6 rounded-lg shadow-lg mt-6">
  <h1 class="text-3xl font-bold mb-6">Visits for <%= @unit.name %></h1>

  <div class="space-y-4" id="visits">
    <% @visits.each do |visit| %>
      <div class="bg-gray-700 p-4 rounded-lg hover:bg-gray-600 transition">
        <p><strong>Visitor:</strong> <%= link_to visit.visitor.name, visitor_path(visit.visitor.id) %></p>
        <p><strong>Date:</strong> <%= visit.date_time %></p>
        <p><strong>Status:</strong> <%= visit.status %></p>
        <p><strong>Unit:</strong> <%= visit.unit.name %></p>
      </div>
    <% end %>
  </div>

  <div class="mt-6">
    <%= link_to 'Back to Units', units_path, class: "bg-gray-600 hover:bg-gray-700 px-4 py-2 rounded-lg transition" %>
  </div>
</div>