config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}
  resources :users, only: [:index, :edit, :update, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")

  get "/home", to: "web#index"
  get "/dashboard", to: "web#dashboard"

  resources :units do
    member do
      get "sectors"
      get "visits", to: "units#visits"
    end
  end
  resources :sectors do
    member do
      get "users"
    end
  end
  resources :visitors do
    collection do
      post :verify_by_cpf
    end
  end
  resources :visits

  root "web#index"
end

app/views/web/dashboard.html.erb
<% if current_user.admin? %>
<div class="max-w-auto mx-auto bg-gray-800 text-white p-6 rounded-lg shadow-lg mt-6">
<div class="admin-info mt-6 p-6 bg-gray-800 text-white rounded-lg">
  <h2 class="text-xl font-bold mb-4">Application Information</h2>
  <div class="grid grid-cols-2 gap-4">
    <p><strong>Total users:</strong> <%= User.count %></p>
    <p><strong>Total visits:</strong> <%= Visit.count %></p>
    <p><strong>Total sectors:</strong> <%= Sector.count %></p>
    <p><strong>Total units:</strong> <%= Unit.count %></p>
    <p><strong>Total visitors:</strong> <%= Visitor.count %></p>
    <p><strong>Confirmed Users:</strong> <%= User.where.not(confirmed_at: nil).count %></p>
    <p><strong>Unconfirmed Users:</strong> <%= User.where(confirmed_at: nil).count %></p>
    <p><strong>Pending Visits:</strong> <%= Visit.where(status: 0).count %></p>
    <p><strong>Completed Visits:</strong> <%= Visit.where(status: 1).count %></p>
    <p><strong>Last Registered User:</strong> <%= User.order(created_at: :desc).first.try(:name) %></p>
  </div>
</div>

  <div class="overflow-x-auto bg-gray-700 p-6 rounded-lg shadow-lg mt-6">
  <div class="mb-6">
    <h1 class="text-3xl text-white font-bold">Users in the system</h1>
  </div>
  <table class="w-full text-white rounded-lg border border-gray-600">
    <thead>
      <tr class="bg-gray-800 text-left">
        <th class="py-3 px-4 border-b border-gray-600">Name</th>
        <th class="py-3 px-4 border-b border-gray-600">Email</th>
        <th class="py-3 px-4 border-b border-gray-600">Role</th>
        <th class="py-3 px-4 border-b border-gray-600">RG</th>
        <th class="py-3 px-4 border-b border-gray-600">CPF</th>
        <th class="py-3 px-4 border-b border-gray-600">Telephone</th>
        <th class="py-3 px-4 border-b border-gray-600">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr class="hover:bg-gray-600 border-b border-gray-600 mt-4">
          <td class="py-3 px-4"><%= user.name %></td>
          <td class="py-3 px-4"><%= user.email %></td>
          <td class="py-3 px-4"><%= user.role %></td>
          <td class="py-3 px-4"><%= user.rg %></td>
          <td class="py-3 px-4"><%= user.cpf %></td>
          <td class="py-3 px-4"><%= user.telephone %></td>
          <td class="py-3 px-4 flex space-x-2">
            <%= link_to 'Edit', edit_user_path(user), class: "bg-yellow-500 hover:bg-yellow-600 px-2 py-1 rounded-lg transition" %>
            <%= button_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?', turbo_confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-600 px-2 py-1 rounded-lg transition" %>          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="mt-6 mx-2">
    <%= link_to 'Register new user', new_user_registration_path, class: "mt-3 bg-green-600 hover:bg-green-700 px-4 py-2 rounded-lg transition" %>
  </div>
</div>

<div class="mx-2 flex justify-between">
  <div class="mt-6 mx-2">
    <%= link_to 'Units', units_path, class: "mt-3 bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg transition" %>
  </div>

  <div class="mt-6 mx-2">
    <%= link_to 'Visitors', visitors_path, class: "mt-3 bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg transition" %>
  </div>

  <div class="mt-6 mx-2">
    <%= link_to 'Sectors', sectors_path, class: "mt-3 bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg transition" %>
  </div>
</div>

</div>
<% end %>

app/views/web/index.html.erb
<div class="bg-gray-700 py-24 sm:py-32">
  <div class="hidden sm:absolute sm:-top-10 sm:right-1/2 sm:-z-10 sm:mr-10 sm:block sm:transform-gpu sm:blur-3xl" aria-hidden="true">
    <div class="aspect-1097/845 w-[68.5625rem] bg-linear-to-tr from-[#ff4694] to-[#776fff] opacity-20" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
  </div>
  <div class="absolute -top-52 left-1/2 -z-10 -translate-x-1/2 transform-gpu blur-3xl sm:top-[-28rem] sm:ml-16 sm:translate-x-0 sm:transform-gpu" aria-hidden="true">
    <div class="aspect-1097/845 w-[68.5625rem] bg-linear-to-tr from-[#ff4694] to-[#776fff] opacity-20" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
  </div>
  <div class="mx-auto max-w-7xl px-6 lg:px-8">
    <div class="mx-auto max-w-2xl lg:mx-0">
      <h2 class="text-5xl font-semibold tracking-tight text-white sm:text-7xl">About the project</h2>
      <p class="mt-8 text-lg font-medium text-pretty text-gray-300 sm:text-xl/8">The system aims to store records of entries of people (visitors) who frequent a specific unit of an institution.</p>
    </div>
    <div class="mx-auto mt-10 max-w-2xl lg:mx-0 lg:max-w-none">
      <div class="grid grid-cols-1 gap-x-8 gap-y-6 text-base/7 font-semibold text-white sm:grid-cols-2 md:flex lg:gap-x-10">
        <a href="https://github.com/Keyllian7/Dunnas-Challenge">Project repository <span aria-hidden="true">&rarr;</span></a>
        <a href="https://www.youtube.com/playlist?list=PLPFcnwFvZAMZfgLLpt17qpilg_pPwBkm4">Development process <span aria-hidden="true">&rarr;</span></a>
        <a href="https://www.linkedin.com/in/keyllian-azevedo/">My LinkedIn <span aria-hidden="true">&rarr;</span></a>
      </div>
    </div>
  </div>
</div>