config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}
  resources :users, only: [:index, :edit, :update, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")

  get "/home", to: "web#index"
  get "/dashboard", to: "web#dashboard"

  resources :units do
    member do
      get "sectors"
      get "visits", to: "units#visits"
    end
  end
  resources :sectors do
    member do
      get "users"
    end
  end
  resources :visitors do
    collection do
      post :verify_by_cpf
    end
  end
  resources :visits

  root "web#index"
end

app/views/layouts/_mailer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style>
      body {
        background-color: #2d3748;
        color: #e2e8f0;
        font-family: Arial, sans-serif;
        padding: 20px;
      }
      .container {
        background-color: #4a5568;
        padding: 20px;
        border-radius: 8px;
        color: #e2e8f0;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="max-h-full bg-gray-500">

    <p class="notice bg-green-500"><%= notice %></p>
    <p class="alert bg-red-500"><%= alert %></p>

    <nav class="bg-gray-800 text-white p-4 shadow-md">
      <div class="container mx-auto flex items-center justify-between">
    
      <div class="flex items-center space-x-4">

      <% if user_signed_in? %>
        <%= link_to (image_tag current_user.photo.url, class: "w-10 h-10 rounded-full border-2 border-white object-cover"), edit_user_registration_path %>
        <span class="text-sm text-gray-300"><%= current_user.remote_photo_url %></span>
      <%= link_to "Home", root_path, class: "text-lg font-semibold hover:text-gray-300 transition" %>
        <% if can? :manage, :all %>
          <%= link_to "Dasboard", dashboard_path, class: "text-lg font-semibold hover:text-gray-300 transition" %>
        <% end %>
      <% end %>
      </div>

      <div class="hidden md:flex items-center space-x-6">
      <% if user_signed_in? %>
        <% if can? :read, Unit%>
          <%= link_to "Units", units_path, class: "hover:text-gray-300 transition" %>
        <% end %>
        <% if can? :read, Sector%>
          <%= link_to "Sectors", sectors_path, class: "hover:text-gray-300 transition" %>
        <% end %>
        <% if can? :read, Visitor%>
          <%= link_to "Visitors", visitors_path, class: "hover:text-gray-300 transition" %>
        <% end %>
        <% if can? :read, Visit%>
          <%= link_to "Visit", visits_path, class: "hover:text-gray-300 transition" %>
        <% end %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "bg-red-600 px-4 py-2 rounded-lg hover:bg-red-700 transition" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "hover:text-gray-300 transition" %>
      <% end %>
      </div>
</nav>


    <%= yield %>
  </body>
</html>